# Generated by Django 2.2.10 on 2020-05-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(default='ryba*100!!!!!!', max_length=500),
        ),
    ]
